### ISSUE TITLE
This currently only pulls the latest .net not the latest monthly cumulative update

### ISSUE THREAD

**Issue by CBSDMKelly** [rbalsleyMSFT/FFU#22]
https://github.com/rbalsleyMSFT/FFU/blob/bfa1ea7d9f33bf2c70e5ec61d34248e4a30ef99c/FFUDevelopment/BuildFFUVM.ps1#L2199
####  The issue:
The current code only locates the latest .NET update. it fails to download the latest cumulative update.

####  Including the date at the front of the search string resolves the issue for me:
**2024-04** Cumulative update for Windows 11 Version 23h2 for x64

The code below resolves the issue and locates the monthly cumulative update.
$Date = get-date -UFormat %Y-%m
$Name = "$Date Cumulative update for Windows $WindowsRelease Version $WindowsVersion for $WindowsArch"

**Comment by rbalsleyMSFT** [comment]
Thanks. The intent was for the $Name variable to also include the double quotes in the search. Without them, it looks like the 'D' release (preview releases) are jumping the list and causing an issue where the .net preview release shows up first. The script just grabs the first in the list.

I've fixed it and will update the release later this week/next. Thanks again.

**Comment by Em3xus-MW** [comment]
Hi,

Apologies if adding to this closed ticket is not the correct way to mention, but I have been having the same issue with cumulative updates not being injected and installed automatically since December 2024. 

I have created a fresh FFU with the latest updates as of last week, 18-February, and it did not pick up the following monthly update which downloads on every machine I deploy. This takes around 1-2 hours to download and then apply so it is adding quite a bit of time to the process.

- 2025-02 Cumulative Update for Windows 11 Version 23H2 for x64-based Systems (KB5051989)

Is there any way to get this rectified to reduce the deployment time? Happy to provide any logs you need.


Thanks

**Comment by rbalsleyMSFT** [comment]
Can you add your FFUDevelopment.log? Also, are you specifying `-WindowsVersion '23h2'`? If you aren't, and you're deploying 23h2 media, you'll need to, otherwise the script defaults to 24h2 and it'll download the checkpoint CU (these are new in 24h2) and try to apply it, which will fail.

**Comment by Em3xus-MW** [comment]
FFUDevelopment.log attached

This is my run command, not currently specifying WindowsVersion so that definitely makes sense! I'll update this with -WindowsVersion '23h2' and give that a crack!

.\BuildFFUVM.ps1 -ISOPath "C:\FFUDevelopment\ISO\SW_DVD9_Win_Pro_11_23H2.14_64BIT_English_Pro_Ent_EDU_N_MLF_X23-94592.ISO" -ProductKey "XXXXX" -Installapps $true -InstallOffice $true -CopyDrivers $false -VMSwitchName 'External' -VMHostIPAddress '192.168.80.92' -CreateDeploymentMedia $true -BuildUSBDrive $false -UpdateLatestCU $true -UpdateLatestNet $true -UpdateLatestDefender $true -UpdateEdge $true -UpdateOneDrive $true -CopyPPKG $true -CopyUnattend $true -verbose


Thanks

[FFUDevelopment.log](https://github.com/user-attachments/files/19018770/FFUDevelopment.log)

**Comment by Em3xus-MW** [comment]
Hi again! Adding the WindowsVersion '23h2' switch to the command has worked thank you. Cutting my deployment times down to less than a quarter of before.

Many thanks.
