### ISSUE TITLE
Feature Request: User Interface?

### ISSUE THREAD

**Issue by AyySorento** [rbalsleyMSFT/FFU#97]
Maybe this was already thought about... but what are the chances this tool will someday have a GUI to help configure everything instead of working out a long command with proper switches? 

In my testing, FFU is fantastic but for entry-level technicians, it's very intimidating to make an installation media, even with highly detailed instructions. Having some type of GUI to simply check the options you want/don't want or easily open file locations to stage software/drivers would be a game changer. The GUI could then print out a command to run or at the click of a button, run the command for you and display all the needed output. Whether it's super minimal or extremely detailed, a GUI would make this tool a game changer and easier to understand for a large group of people. 

Thanks. :)

**Comment by rbalsleyMSFT** [comment]
Thanks for the feedback.

I've gotten this feedback before and have thought through it as the tool as grown. It's definitely possible to write one, but no plans right now to do so. Maybe sometime next year as I get some free time. Right now there's a lot of work for 2410.1 that's been delayed until December that we're putting in.

Thanks,
Richard

From: Sorento ***@***.***>
Sent: Friday, November 15, 2024 9:09 AM
To: rbalsleyMSFT/FFU ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rbalsleyMSFT/FFU] Feature Request: User Interface? (Issue #97)


Maybe this was already thought about... but what are the chances this tool will someday have a GUI to help configure everything instead of working out a long command with proper switches?

In my testing, FFU is fantastic but for entry-level technicians, it's very intimidating to make an installation media, even with highly detailed instructions. Having some type of GUI to simply check the options you want/don't want or easily open file locations to stage software/drivers would be a game changer. The GUI could then print out a command to run or at the click of a button, run the command for you and display all the needed output. Whether it's super minimal or extremely detailed, a GUI would make this tool a game changer and easier to understand for a large group of people.

Thanks. :)

-

**Comment by rbalsleyMSFT** [comment]
Closing. Thanks for the feedback. With 2412.1 configuration file support has been added, which should help make things a bit easier. This paves the way for a potential UI.
